### PR TITLE
Upgrade Cordova to 2.1.0

### PR DESCRIPTION
**Pull request by krtek**
Upgraded Cordova to newest version.

### CODE REVIEW

**Comment by edharmesh** [comment]
So it seems no change is required in the plugin code when you upgrade from Cordova 2.0 to Cordova 2.1.

**Comment by marknutter** [comment]
sounds good!

**Comment by FullMontag** [comment]
The plugin works on PG 2.2 as well :)

On Thu, Jan 17, 2013 at 7:53 AM, Mark Nutter notifications@github.comwrote:

> sounds good!
> 
> On Wed, Jan 16, 2013 at 11:16 AM, edharmesh notifications@github.comwrote:
> 
> > So it seems no change is required in the plugin code when you upgrade
> > from
> > Cordova 2.0 to Cordova 2.1.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/marknutter/GCM-Cordova/pull/4#issuecomment-12329215>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/marknutter/GCM-Cordova/pull/4#issuecomment-12355519.

## 

Best,
Nir

Co-founder
+972-54-3944493
www.fabulagame.com

**Comment by edharmesh** [comment]
My previous comment was just based on seeing the diff of this pull request. But for some reason this plugin is not working for me. On the phone screen, last message I see is "calling GCMRegistrar.register, register our Sender ID with Google". But in LogCat, I see below error, which means "window.GCM" is not defined. Any help?

01-17 08:48:07.745: D/CordovaLog(14755): Uncaught TypeError: Cannot call method 'register' of undefined
01-17 08:48:07.745: D/CordovaLog(14755): file:///android_asset/www/CORDOVA_GCM_script.js: Line 36 : Uncaught TypeError: Cannot call method 'register' of undefined

**Comment by marknutter** [comment]
register not being defined would suggest that the GCMPlugin.js file is not
being included properly or that cordova is not loading properly. Double
check to make sure you actually have a window.plugins variable available
and that GCMPlugin.js is actually being loaded before using
CORDOVA_GCM_script.js.

Mark

**Comment by edharmesh** [comment]
I figured the problem was that GCM object was defined locally in
GCMPlugin.js.

It worked after replacing GCMPlugin.js with the same file in the
"refactoring" pull request by gumieri.

I believe the variables defined within "(function () {" stay local to that
block in javascript. guimieri's refactoring pulls the GCM object out of
that, and defines it globally, which makes the GCM object accessible
in CORDOVA_GCM_script.js

**Comment by marknutter** [comment]
cool, sounds good!

Mark

**Comment by edharmesh** [comment]
I am not sure what else is valuable in that pull request. Are you going to vet and merge that pull request?

**Comment by marknutter** [comment]
Merged!

**Comment by krtek** [comment]
Thanks!

**Comment by Brijesh1111** [comment]
Hi, i have downloaded latest code today and i am getting same error as below

01-17 08:48:07.745: D/CordovaLog(14755): file:///android_asset/www/CORDOVA_GCM_script.js: Line 36 : Uncaught TypeError: Cannot call method 'register' of undefined

Please help ? 

Thanks
Brijesh

**Comment by Ekomak** [comment]
Il coins in thé code Thatcher thé fonction résister don't existe in thé
demo app i'll try a redéfinition offre this function

**Comment by Brijesh1111** [comment]
Thanks marc. meanwhile let me know if any quick fix i can do to overcome this issue.

**Comment by JeanetteAndersen** [comment]
I've the same problem as Brijesh1111.

file:///android_asset/www/CORDOVA_GCM_script.js: Line 36 : Uncaught TypeError: Cannot call method 'register' of undefined

Is there any solution for this?

Thanks,
Jeanette

**Comment by marknutter** [comment]
I will take a look at this today

Mark

**Comment by phpsa** [comment]
Hi, as the author not come back yet:
had the same issue, as a temporary fix (as this is not the correct way)
in CORDOVA_GCM_script.js
change 
window.GCM.register("xxx", "GCM_Event", GCM_Success, GCM_Fail );
to 
 if( window.plugins){
        window.plugins.GCM.register("xxx", "GCM_Event", GCM_Success, GCM_Fail );
    }else{
        window.GCM.register("xxx", "GCM_Event", GCM_Success, GCM_Fail );
    }

**Comment by JeanetteAndersen** [comment]
I've just had time to try phpsa's fix now, and it works for me :)

Thank you phpsa

**Comment by marknutter** [comment]
I have applied this fix to the plugin and its working for me as well. Thanks phpsa

Mark
—

**Comment by wajih775** [comment]
Here is catlog Output on android but u can see not getting register ID even not trigering GCM Event in used window.plugins.GCM.register(“my_app_id”, “GCM_Event”, GCM_Success, GCM_Fail );

Please any one tell me what’s the prolem where i am wrong, using cordova 2.7.0
i am totally tired from this problem but still not resoled it . any one have know about this please help.

11-09 20:17:06.180: I/CordovaLog(1245): Changing log level to DEBUG(3)
11-09 20:17:06.190: I/CordovaLog(1245): Found preference for useBrowserHistory=true
11-09 20:17:06.190: D/CordovaLog(1245): Found preference for useBrowserHistory=true
11-09 20:17:06.190: I/CordovaLog(1245): Found preference for exit-on-suspend=false
11-09 20:17:06.190: D/CordovaLog(1245): Found preference for exit-on-suspend=false
11-09 20:17:06.220: D/DroidGap(1245): DroidGap.onCreate()
11-09 20:17:06.550: D/CordovaWebView(1245): CordovaWebView is running on device made by: unknown
11-09 20:17:06.570: D/JsMessageQueue(1245): Set native->JS mode to 2
11-09 20:17:06.603: D/DroidGap(1245): DroidGap.init()
11-09 20:17:06.640: D/CordovaWebView(1245): >>> loadUrl(file:///android_asset/www/index.html)
11-09 20:17:06.654: D/PluginManager(1245): init()
11-09 20:17:06.700: D/CordovaWebView(1245): >>> loadUrlNow()
11-09 20:17:06.700: D/DroidGap(1245): Resuming the App
11-09 20:17:06.780: D/SoftKeyboardDetect(1245): Ignore this event
11-09 20:17:06.900: I/Choreographer(1245): Skipped 125 frames! The application may be doing too much work on its main thread.
11-09 20:17:06.990: D/gralloc_goldfish(1245): Emulator without GPU emulation detected.
11-09 20:17:07.271: I/Choreographer(1245): Skipped 190 frames! The application may be doing too much work on its main thread.
11-09 20:17:07.271: D/SoftKeyboardDetect(1245): Ignore this event
11-09 20:17:07.400: D/DroidGap(1245): onMessage(onPageStarted,file:///android_asset/www/index.html)
11-09 20:17:10.820: D/chromium(1245): Unknown chromium error: -6
11-09 20:17:11.450: D/dalvikvm(1245): GC_FOR_ALLOC freed 301K, 13% free 2718K/3100K, paused 38ms, total 41ms
11-09 20:17:11.460: D/CordovaNetworkManager(1245): Connection Type: 3g
11-09 20:17:11.460: D/DroidGap(1245): onMessage(networkconnection,3g)
11-09 20:17:11.470: D/CordovaNetworkManager(1245): Connection Type: 3g
11-09 20:17:11.492: D/DroidGap(1245): onMessage(spinner,stop)
11-09 20:17:11.570: D/Cordova(1245): onPageFinished(file:///android_asset/www/index.html)
11-09 20:17:11.570: D/DroidGap(1245): onMessage(onPageFinished,file:///android_asset/www/index.html)
11-09 20:17:11.660: V/GCMPlugin:execute(1245): action=register
11-09 20:17:11.670: V/GCMPlugin:execute(1245): data=[{"senderID":"XXXXXXXXXX","ecb":"GCM_Event"}]
11-09 20:17:11.690: V/GCMPlugin:execute(1245): jo={“senderID”:”XXXXXXXXXX”,”ecb”:”GCM_Event”}
11-09 20:17:11.690: V/GCMPlugin:execute(1245): ECB=GCM_Event senderID=XXXXXXXXXX
11-09 20:17:11.700: V/GCMRegistrar(1245): Registering receiver
11-09 20:17:11.710: D/GCMRegistrar(1245): resetting backoff for org.apache.cordova.example
11-09 20:17:11.740: V/GCMRegistrar(1245): Registering app org.apache.cordova.example of senders XXXXXXXXXX
11-09 20:17:11.760: V/GCMPlugin:execute(1245): GCMRegistrar.register called
11-09 20:17:11.820: D/TilesManager(1245): Starting TG #0, 0x2a234580

**Pull request merged**
