### PR TITLE
Support Cordova 2.7

### PR DESCRIPTION
**Pull request by roshammar**
The plugin wouldn't compile with Cordova 2.7 due to some API updates.

(This is my first pull request ever on GH, so please let me know if I could improve anything)

### CODE REVIEW

**Comment by romainbraun** [comment]
I think it would be better to use callbackContext.success() instead of sending JS to the webView. But I could be wrong.

**Comment by glutorange** [comment]
Works for me, great work!

**Comment by marknutter** [comment]
Thanks @roshammar !

**Comment by roshammar** [comment]
@marknutter Happy to help!

**Pull request merged**
